Controllers/CustomerController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Vidly.Models;
using System.Web.UI.WebControls;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;

        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }




        // GET: Customer
        public ActionResult CreateOrEditCustomer()
        {
            var MembershipTypesList = _context.MembershipTypes.ToList();

            var viewModel = new NewCustomerViewModel {
                MembershipTypes = MembershipTypesList };

                return View("CreateOrEditCustomer",viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrUpdateCustomer(Customer customer)
        {
            ModelState.Remove("customer.Id");
            if (ModelState.IsValid)
            {
                if (customer.Id == 0)
                { 
                    _context.Customers.Add(customer);
                    _context.SaveChanges();
                    ModelState.Clear();
                    ViewBag.SuccessMessage = "Registeration Successful";
                    return RedirectToAction("CreateOrEditCustomer");

                }
                else
                {
                    
                    _context.Entry(customer).State = EntityState.Modified;
                    _context.SaveChanges();
                    ModelState.Clear();
                    ViewBag.SuccessMessage = "Details Updated Successfully";
                    return RedirectToAction("CustomerList");
                }
            }
                    return RedirectToAction("CreateOrEditCustomer");
            

        }
        public ActionResult CustomerList()
        {
            //var viewModel = new CustomerViewModel
            //{
            //    Customers = _context.Customers.ToList(),
            //    MembershipTypes=_context.MembershipTypes.ToList()
            //};
            return View(/*viewModel*/);
        }

        public ActionResult CustomerDetails(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();
            return View(customer);
        }

        public ActionResult RemoveCustomer(int Id)
        {
           Customer customer = _context.Customers.Where(x => x.Id.Equals(Id)).First();
            _context.Customers.Remove(customer);
            _context.SaveChanges();
            return RedirectToAction("CustomerList");

        }

        public ActionResult EditCustomer(int Id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == Id);

            if (customer == null)
                return HttpNotFound();

            var viewModel = new NewCustomerViewModel
            {
                Customer = customer,
                MembershipTypes = _context.MembershipTypes.ToList(),
            };
            return View("CreateOrEditCustomer",viewModel);
           

        }
    }
}

Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class MovieController : Controller
    {
        private ApplicationDbContext _context;

        public MovieController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Movie
        public ActionResult CreateOrEditMovie()
        {
            var GenreTypes = _context.movieGenres.ToList();

            var viewModel = new NewMovieViewModel
            {
                MovieGenres = GenreTypes
            };

            return View("CreateOrEditMovie", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrUpdateMovie(Movie movie)
        {
            ModelState.Remove("movie.Id");
            if (ModelState.IsValid)
            {
                if (movie.Id == 0)
                {
                    //movie.Genre = _context.movieGenres.Where(g => g.Id == movie.GenreId).FirstOrDefault();
                    _context.Movies.Add(movie);
                    _context.SaveChanges();
                    ModelState.Clear();
                    ViewBag.SuccessMessage = "Registeration Successful";
                    return RedirectToAction("CreateOrEditMovie");

                }
                else
                {

                    _context.Entry(movie).State = EntityState.Modified;
                    _context.SaveChanges();
                    ModelState.Clear();
                    ViewBag.SuccessMessage = "Details Updated Successfully";
                    return RedirectToAction("MovieList");
                }
            }
            return RedirectToAction("CreateOrEditMovie");


        }
        public ActionResult MovieList()
        {
            var viewModel = new MovieViewModel
            {
                Movies = _context.Movies.ToList(),
                Genres = _context.movieGenres.ToList()
            };
            return View(viewModel);
        }

        public ActionResult MovieDetails(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
                return HttpNotFound();
            return View(movie);
        }

        public ActionResult RemoveMovie(int Id)
        {
            Movie movie = _context.Movies.Where(m => m.Id.Equals(Id)).First();
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            return RedirectToAction("CustomerList");

        }

        public ActionResult EditMovie(int Id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == Id);

            if (movie == null)
                return HttpNotFound();

            var viewModel = new NewMovieViewModel
            {
                Movie = movie,
                MovieGenres = _context.movieGenres.ToList(),
            };
            return View("CreateOrEditMovie", viewModel);


        }
    }
}

Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Vidly</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/Unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
    
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

</body>
</html>

Views/Shared/_NavBar.cshtml
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">VIDLY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CreateOrEditCustomer","Customer")">Customer Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CustomerList","Customer")">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CreateOrEditMovie","Movie")">Add Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("MovieList","Movie")">Movie List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("New","Rentals")">Rental Form</a>
                </li>

            </ul>
            <div>
                @Html.Partial("_LoginPartial")
            </div>
                


        </div>
        
    </nav>